ALTER TABLE YD_COMPARE_RESULT ADD (NAME1 CLOB);

UPDATE YD_COMPARE_RESULT SET NAME1=TO_CHAR(YD_COLUMN_COLOR);
COMMIT;

ALTER TABLE YD_COMPARE_RESULT DROP COLUMN YD_COLUMN_COLOR;

ALTER TABLE YD_COMPARE_RESULT RENAME COLUMN NAME1 TO YD_COLUMN_COLOR;