ALTER TABLE "YD_CUSTOMER_PUBLIC_MID" MODIFY ("YD_BUSINESS_SCOPE_ECCS" VARCHAR2(500 CHAR) );
ALTER TABLE "YD_CUSTOMER_PUBLIC" MODIFY ("YD_BUSINESS_SCOPE_ECCS" VARCHAR2(500 CHAR) );
ALTER TABLE "YD_CUSTOMER_PUBLIC_LOG" MODIFY ("YD_BUSINESS_SCOPE_ECCS" VARCHAR2(500 CHAR) );
ALTER TABLE "YD_CORE_COLLECTION" MODIFY ("YD_BUSINESS_SCOPE_ECCS" VARCHAR2(500 CHAR) );