ALTER TABLE YD_ANNUAL_RESULT ADD (NAME1 CLOB);

UPDATE YD_ANNUAL_RESULT SET NAME1=TO_CHAR(YD_COMPARE_RESULT);
COMMIT;

ALTER TABLE YD_ANNUAL_RESULT DROP COLUMN YD_COMPARE_RESULT;

ALTER TABLE YD_ANNUAL_RESULT RENAME COLUMN NAME1 TO YD_COMPARE_RESULT;