ALTER TABLE YD_COMPARE_RESULT ADD (NAME1 CLOB);

UPDATE YD_COMPARE_RESULT SET NAME1=TO_CHAR(YD_ROW_CONTENT);
COMMIT;

ALTER TABLE YD_COMPARE_RESULT DROP COLUMN YD_ROW_CONTENT;

ALTER TABLE YD_COMPARE_RESULT RENAME COLUMN NAME1 TO YD_ROW_CONTENT;